### ISSUE TITLE
Using division outside of `calc()` is deprecated starting from`dart-sass` 1.44.0

### ISSUE THREAD

**Issue by psimk** [mediamonks/scss-utils#15]
I am getting the following deprecation warning from [dart-sass](https://github.com/sass/dart-sass/)
![image](https://user-images.githubusercontent.com/21334130/148046445-553da29a-a0bd-436e-bf8b-fdb814d1afe6.png)

**Comment by pigeonfresh** [comment]
We need to update things when we can use dart sass 2.0
We can't fix this yet

**Comment by pigeonfresh** [comment]
More info:
https://sass-lang.com/documentation/breaking-changes/slash-div

**Comment by psimk** [comment]
scroll down on that page, we can already switch to this, it would however require a major release of `seng-scss`
![image](https://user-images.githubusercontent.com/21334130/148047745-0f0cfcf8-cfd1-4e36-991a-ebdbf12836db.png)

**Comment by psimk** [comment]
@pigeonfresh 
As per SASS's recommendations I think we can use `sass-migration` to quickly solve this:

```bash
npx sass-migrator division **/*.scss
```
